In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.10.0+cu130'

In [3]:
torch.cuda.is_available()

True

In [4]:
print(torch.version.cuda)

13.0


In [5]:
x = torch.tensor([1,2,3], device='cuda', dtype=torch.float32)
y = torch.tensor([1,2,3], device='cuda', dtype=torch.float32)
x

tensor([1., 2., 3.], device='cuda:0')

In [6]:
x+y

tensor([2., 4., 6.], device='cuda:0')

In [7]:
np_arr = np.array([1,2,3])

In [8]:
x.cpu().numpy()

array([1., 2., 3.], dtype=float32)

como le hice cuda se copio si no no se copia!

In [9]:
pt_tensor = torch.from_numpy(np_arr).to('cuda')
other = torch.tensor(np_arr)

In [10]:
np_arr[0] = 999

In [11]:
pt_tensor

tensor([1, 2, 3], device='cuda:0')

tensor([1, 2, 3])